[build]
  command = "npm install"  
  publish = "dist"          

[functions]
  # If using serverless functions

[dev]
  command = "node server"      # For local dev (optional)

# For Node.js servers (if applicable)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 5000